name: Weather CLI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
      
    - name: Build and run tests
      run: |
        mkdir -p bin
        make test
        
    - name: Clean up
      if: always()
      run: make clean